[package]
name = "lapsus_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
cidre = "0.11.5"
core-graphics = "0.25.0"
objc2-app-kit = "0.3.2"
objc2-core-foundation = "0.3.2"
objc2 = "0.6.3"
log = "0.4.29"
env_logger = "0.11.8"

[dependencies.macos_multitouch]
path = "macos-multitouch"
