[env]
MAXIMUM_MOMENTUM_SPEED = "9000.0"
TRACKPAD_VELOCITY_GAIN = "0.95"
GLIDE_DECAY_PER_SECOND = "6.5"
MINIMUM_GLIDE_VELOCITY = "220.0"
GLIDE_STOP_SPEED_FACTOR = "0.45"
VELOCITY_SMOOTHING = "0.2"
MIN_DT = "0.002"
MULTI_FINGER_SUPPRESSION_DEADLINE = "0.15"